/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarAlign */

#ifndef _Included_com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarAlign
#define _Included_com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarAlign
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarAlign
 * Method:    tranFastq
 * Signature: (J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarAlign_tranFastq
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarAlign
 * Method:    runStar
 * Signature: (J[[C)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarAlign_runStar
  (JNIEnv *, jobject, jlong, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
