/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarInit */

#ifndef _Included_com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarInit
#define _Included_com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarInit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarInit
 * Method:    getAddress
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarInit_getAddress
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
