/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarInit */

#ifndef _Included_com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarInit
#define _Included_com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarInit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarInit
 * Method:    openParameters
 * Signature: (I[[C)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarInit_openParameters
  (JNIEnv *, jclass, jint, jobjectArray);

/*
 * Class:     com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarInit
 * Method:    openStar
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_com_github_xmuyulab_sparkscRNAseq_algorithms_adapter_StarInit_openStar
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
